SistemaLudico/ViewModels/MainStudent/GameViewModel.cs
using SistemaLudico.Controllers;
using SistemaLudico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaLudico.ViewModels.MainStudent
{
    public class GameViewModel
    {
        public Int32? TemaId { set; get; }
        public String LevelBIA { set; get; }
        public Int32? JuegoId { set; get; }
        public List<Ejercicio> ListLevelBIA { set; get; } = new List<Ejercicio>();
        public List<Progreso> ListProgreso { set; get; } = new List<Progreso>();
        public Boolean ActivateCalificacion { set; get; }
        HttpContext context = HttpContext.Current;

        public void Fill(CargarDatosContext cd, Int32? temaId, String levelBIA) {
            this.TemaId = temaId;
            this.LevelBIA = levelBIA;
            this.ListLevelBIA = cd.context.Ejercicio.Where(x => x.LevelBIA == this.LevelBIA && x.TemaId == this.TemaId).OrderBy(x=>x.LevelGame).ToList();
            this.JuegoId = cd.context.Ejercicio.FirstOrDefault(x => x.LevelBIA == this.LevelBIA && x.TemaId == this.TemaId).JuegoId;
            var participanteId = (int)(context.Session["PARTICIPANTEID"]);
            var lstProgreso = cd.context.Progreso.Where(x => x.ParticipanteId == participanteId && x.Ejercicio.JuegoId == JuegoId && x.Ejercicio.LevelBIA == LevelBIA && x.Nota > 0).ToList();
            this.ListProgreso = cd.context.Progreso.Where(x => x.ParticipanteId == participanteId && x.Ejercicio.JuegoId == JuegoId && x.Ejercicio.LevelBIA == LevelBIA).ToList(); ;
            if (lstProgreso.Count() == 5) {
                this.ActivateCalificacion = true;
            }
            else{
                this.ActivateCalificacion = false;
            }
        }
    }
}

SistemaLudico/ViewModels/MainStudent/LevelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaLudico.ViewModels.MainStudent
{
    public class LevelViewModel
    {
        public Int32? TemaId { set; get; }
        public void Fill(Int32? temaId) {
            this.TemaId = temaId;
        }
    }
}

SistemaLudico/ViewModels/MainStudent/ResultViewModel.cs
using SistemaLudico.Controllers;
using SistemaLudico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaLudico.ViewModels.MainStudent
{
    public class ResultViewModel
    {
        public string MensajeFinal { set; get; }
        public Ejercicio Ejercicio { set; get; } = new Ejercicio();
        HttpContext context = HttpContext.Current;
        public List<Tuple<string, int>> ListDetailNota { set; get; } = new List<Tuple<string, int>>();

        public void Fill(CargarDatosContext cd, Int32? EjercicioId, Int32? Vidas) {
            this.Ejercicio = new Ejercicio();
            this.Ejercicio = cd.context.Ejercicio.FirstOrDefault(x => x.EjercicioId == EjercicioId);
            var nota = 0;
            var participanteId = (int)(context.Session["PARTICIPANTEID"]);
            switch (Vidas) {
                case 1:
                    this.MensajeFinal = "Haz obtenido 2 puntos";
                    nota = 2;
                    break;
                case 2:
                    this.MensajeFinal = "Haz obtenido 3 puntos";
                    nota = 3;
                    break;
                case 3:
                    this.MensajeFinal = "Haz obtenido 4 puntos";
                    nota = 4;
                    break;
            }

            var progreso = new Progreso();

            if (cd.context.Progreso.Any(x => x.EjercicioId == EjercicioId && x.ParticipanteId == participanteId))
            {
                progreso = cd.context.Progreso.FirstOrDefault(x => x.EjercicioId == EjercicioId && x.ParticipanteId == participanteId);
                if (nota > progreso.Nota) {
                    progreso.Nota = nota;
                }
                cd.context.SaveChanges();

                //validar si ya existe el siguiente
                var nextLevel = (Ejercicio.LevelGame + 1);
                var ejercicioNext = cd.context.Ejercicio.FirstOrDefault(x => x.LevelGame == nextLevel && x.TemaId == Ejercicio.TemaId);

                if (!cd.context.Progreso.Any(x => x.ParticipanteId == participanteId && x.EjercicioId == ejercicioNext.EjercicioId)) {
                
                    var progresoFuture = new Progreso();
                    cd.context.Progreso.Add(progresoFuture);
                    progresoFuture.ParticipanteId = participanteId;
                    progresoFuture.EjercicioId = ejercicioNext.EjercicioId;
                    progresoFuture.Nota = 0;
                    cd.context.SaveChanges();
                }
            }
            else
            {
                /*cd.context.Progreso.Add(progreso);
                progreso.ParticipanteId = participanteId;
                progreso.EjercicioId = EjercicioId;
                progreso.Nota = nota;
                cd.context.SaveChanges();*/
            }
        }
        public void FillResultLevelBIA(CargarDatosContext cd, Int32? JuegoId, String LevelBIA)
        {
            var participanteId = (int)(context.Session["PARTICIPANTEID"]);
            var puntuacion = new Puntuacion();
            var listProgreso = cd.context.Progreso.Where(x => x.ParticipanteId == participanteId && x.Ejercicio.JuegoId == JuegoId && x.Ejercicio.LevelBIA == LevelBIA).ToList();
            this.Ejercicio = cd.context.Ejercicio.FirstOrDefault(x => x.JuegoId == JuegoId);
            if (cd.context.Puntuacion.Any(x => x.JuegoId == JuegoId && x.ParticipanteId == participanteId && x.LevelBIA == LevelBIA))
            {
                puntuacion = cd.context.Puntuacion.FirstOrDefault(x => x.JuegoId == JuegoId && x.ParticipanteId == participanteId && x.LevelBIA == LevelBIA);
                puntuacion.Nota = listProgreso.Sum(x => x.Nota).Value;
            }
            else
            {
                cd.context.Puntuacion.Add(puntuacion);
                puntuacion.Nota = listProgreso.Sum(x => x.Nota).Value;
                puntuacion.ParticipanteId = participanteId;
                puntuacion.JuegoId = JuegoId.Value;
                puntuacion.LevelBIA = LevelBIA;
            }
            cd.context.SaveChanges();

            foreach(var item in listProgreso) {
                this.ListDetailNota.Add(new Tuple<string, int>("Ejercicio " + item.Ejercicio.LevelGame, item.Nota.Value));
            }

            var level = String.Empty;
            switch (LevelBIA) {
                case "BAS":
                    level = "BÁSICO";
                    break;
                case "INT":
                    level = "INTERMEDIO";
                    break;
                case "AVA":
                    level = "AVANZADO";
                    break;
            }
            var juego = cd.context.Juego.FirstOrDefault(x => x.JuegoId == JuegoId);
            this.MensajeFinal = "Para el nivel " + level + " del tema " + juego.Tema.Nombre + " ha obtenido un total de " + puntuacion.Nota.ToString();
        }
    }
}

SistemaLudico/Controllers/NumerationController.cs
using SistemaLudico.ViewModels.MainStudent;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaLudico.Controllers
{
    public class NumerationController : BaseController
    {
        public ActionResult Level(Int32? TemaId)
        {
            LevelViewModel vm = new LevelViewModel();
            vm.Fill(TemaId);
            return View(vm);
        }
        public ActionResult Games(Int32? TemaId, String LevelBIA)
        {
            GameViewModel vm = new GameViewModel();
            vm.Fill(CargarDatosContext(), TemaId, LevelBIA);
            return View(vm);
        }
        public ActionResult Juego1to5(Int32? TemaId, Int32? LevelGame)
        {
            JuegoViewModel vm = new JuegoViewModel();
            vm.Fill(CargarDatosContext(), TemaId, LevelGame);
            return View(vm);
        }
        public ActionResult Juego6to10(Int32? TemaId, Int32? LevelGame)
        {
            JuegoViewModel vm = new JuegoViewModel();
            vm.Fill(CargarDatosContext(), TemaId, LevelGame);
            return View(vm);
        }

        public ActionResult Result(Int32? EjercicioId, Int32? Vidas)
        {
            ResultViewModel vm = new ResultViewModel();
            vm.Fill(CargarDatosContext(), EjercicioId, Vidas);
            return View(vm);
        }
        public ActionResult ResultByTopic(Int32? JuegoId, String LevelBIA)
        {
            ResultViewModel vm = new ResultViewModel();
            vm.FillResultLevelBIA(CargarDatosContext(), JuegoId, LevelBIA);
            return View(vm);
        }

        public JsonResult Calculate1to5(string Resp, Int32? EjercicioId)
        {
            try
            {
                var ejercicio = context.Ejercicio.FirstOrDefault(x => x.EjercicioId == EjercicioId);
                if (Resp != ejercicio.Resultado)
                {
                    var result = new
                    {
                        value = "false",
                        mensaje = "La operacion es incorrecta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new
                    {
                        value = "true",
                        mensaje = "La operacion es correcta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("false", JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult Calculate6to10(string Resp, Int32? EjercicioId)
        {

            try
            {
                var ejercicio = context.Ejercicio.FirstOrDefault(x => x.EjercicioId == EjercicioId);
                if (Resp != ejercicio.Resultado)
                {
                    var result = new
                    {
                        value = "false",
                        mensaje = "La operacion es incorrecta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new
                    {
                        value = "true",
                        mensaje = "La operacion es correcta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("false", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

SistemaLudico/Views/Numeration/Games.cshtml
@model SistemaLudico.ViewModels.MainStudent.GameViewModel
@{
    ViewBag.Title = "Games";
}

<style>
    body, html {
        height: 100%;
        margin: 0;
    }

    .fondo {
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .centervertical {
        margin: 0;
        position: sticky;
        top: 30%;
        -ms-transform: translateY(-30%);
        transform: translateY(-30%);
    }
    .candado {
        background-image:url('@Url.Content("../../Content/assets/img/iconos/candado.png")');
        background-repeat: no-repeat;
        background-size: 40px 40px;
    }
</style>

<div class="fondo" style="background-image: url('@Url.Content("../../Content/assets/img/fig16.jpg")');">
    <div class="row centervertical">
        <div class="col-lg-1" style="margin-top:10%">
        </div>
        @{ var contador = 0;}
        @foreach (var item in Model.ListLevelBIA)
        {
            if (@contador % 2 == 0)
            {
                <div class="col-lg-2" style="margin-top:8%">
                    @if (Model.ListProgreso.Any(x => x.EjercicioId == item.EjercicioId))
                    {
                        <a class="col-lg-12 button small" style="background-color:blue;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action(item.Juego.Action, item.Juego.Controller, new { TemaId = Model.TemaId, LevelGame = item.LevelGame })">JUEGO @item.LevelGame</a>
                    }
                    else
                    {
                        <a class="col-lg-12 button small @(item.LevelGame == 1 ? "" : "candado")" style="background-color:blue;  color:white;font-size: 20px;font-weight: bold;" data-send data-block>JUEGO @item.LevelGame</a>
                    }
                </div>
            }
            else
            {
                <div class="col-lg-2" style="margin-top:18%">
                    @if (Model.ListProgreso.Any(x => x.EjercicioId == item.EjercicioId))
                    {
                        <a class="col-lg-12 button small" style="background-color:blue;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action(item.Juego.Action, item.Juego.Controller, new { TemaId = Model.TemaId, LevelGame = item.LevelGame })">JUEGO @item.LevelGame</a>

                    }
                    else
                    {
                        <a class="col-lg-12 button small candado" style="background-color:blue;  color:white;font-size: 20px;font-weight: bold;" data-send data-block>JUEGO @item.LevelGame</a>

                    }
                </div>
            }
            contador++;
        }
        <div class="col-lg-1" style="margin-top:10%">
        </div>
    </div>
    <div class="row" style="margin-top:400px">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-2">
            <a class="col-lg-12 button small" style="background-color:red;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("Level","Numeration", new { TemaId = Model.TemaId })">ATRAS</a>
        </div>
        <div class="col-lg-2">
        </div>
        <div class="col-lg-2">
        </div>
        <div class="col-lg-2">
        </div>
        <div class="col-lg-2">
            @if (Model.ActivateCalificacion)
            {
                <a class="col-lg-12 button small" style="background-color:yellow;  color:black;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("ResultByTopic", "Numeration", new { JuegoId = Model.JuegoId, LevelBIA = Model.LevelBIA })">CALCULAR PUNTAJE FINAL</a>
            }
        </div>
    </div>
</div>


@section scripts{
    <script>
       $('[data-block]').on('click', function () {
           Swal.fire(
               "Para desbloquear este nivel debe finalizar los ejercicios anteriores",
               '',
               'warning'
           )
       });
    </script>
}

SistemaLudico/Views/Numeration/Level.cshtml
@model SistemaLudico.ViewModels.MainStudent.LevelViewModel
@{
    ViewBag.Title = "Level";
}

<style>
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;
    }
    body, html {
        height: 100%;
        margin: 0;
    }

    .fondo {
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .centervertical {
        margin: 0;
        position: absolute;
        top: 30%;
        -ms-transform: translateY(-30%);
        transform: translateY(-30%);
    }
</style>

<div class="fondo" style="background-image: url('@Url.Content("../../Content/assets/img/fig16.jpg")')">
    <div class="row">
        <div class="col-lg-4" style="margin-top:10%">
            <img src="@Url.Content("~/Content/assets/img/gift/7.gif")" class="center" width="310" height="310"/>
            <a class="col-lg-12 button small" style="background-color:forestgreen;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("Games","Numeration", new { TemaId = Model.TemaId, LevelBIA = "BAS" })">BASICO</a>
        </div>
        <div class="col-lg-4" style="margin-top:10%">
            <img src="@Url.Content("~/Content/assets/img/gift/3.gif")"class="center" width="310" height="310" />
            <a class="col-lg-12 button small" style="background-color:darkorange;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("Games","Numeration", new { TemaId = Model.TemaId, LevelBIA = "INT"})">INTERMEDIO</a>
        </div>
        <div class="col-lg-4" style="margin-top:10%">
            <img src="@Url.Content("~/Content/assets/img/gift/8.gif")" class="center" width="310" height="310"/>
            <a class="col-lg-12 button small" style="background-color:red;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("Games","Numeration", new { TemaId = Model.TemaId, LevelBIA = "AVA" })">AVANZADO</a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1" style="margin-top:10%">
        </div>
        <div class="col-lg-2" style="margin-top:12%">
            <a class="col-lg-12 button small" style="background-color:red;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("TemaStart","MainStudent", new { TemaId = Model.TemaId })">ATRAS</a>
        </div>
    </div>
</div>

SistemaLudico/Views/Numeration/Result.cshtml
@model SistemaLudico.ViewModels.MainStudent.ResultViewModel
@{
    ViewBag.Title = "Result";
}

<style>
    body, html {
        height: 100%;
        margin: 0;
    }

    .fondo {
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .centervertical {
        margin: 0;
        position: relative;
        top: 30%;
        -ms-transform: translateY(-30%);
        transform: translateY(-30%);
    }
</style>

<div class="fondo" style="background-image: url('@Url.Content("../../Content/assets/img/Fondos/Fondo_Avatar.png")');">


    <div data-reto class="centervertical">
        <br />
        <br />
        <div class="grid grid-4-4-4 centered">
            <div class="grid-column">
                <h1 style="text-align:center; color:black"> Resultado del Juego </h1>
            </div>
        </div>
        <br />
        <div class="grid grid-4-4-4 centered">
            <div class="grid-column">
                <img src="@Url.Content("~/Content/assets/img/gift/s1.gif")" />
            </div>
            <div class="grid-column">
                <img src="@Url.Content("~/Content/assets/img/fig4.PNG")" width="385" height="385" />
            </div>
            <div class="grid-column">
                <img src="@Url.Content("~/Content/assets/img/gift/s2.gif")" />
            </div>
        </div>
        <br />
        <div class="grid grid-4-4-4 centered">
            <div class="grid-column card" style="opacity: 0.8;padding-top: 30px;padding-bottom: 30px;margin-bottom: 10px;">
                <h1 style="text-align:center; color:black;font-size: 60px;font-weight: bold;"> @Model.MensajeFinal </h1>
            </div>
        </div>
        <div class="grid grid-4-4-4 centered">
            <div class="grid-column">
                <a class="btn" style="background-color:green;  color:white;font-size: 20px;font-weight: bold;" href="@Url.Action("Games", "Numeration", new { TemaId = Model.Ejercicio.TemaId, LevelBIA = Model.Ejercicio.LevelBIA})">
                    Pasar al siguiente Juego
                </a>
            </div>
        </div>
    </div>
</div>

SistemaLudico/Views/Numeration/ResultByTopic.cshtml
@model SistemaLudico.ViewModels.MainStudent.ResultViewModel
@{
    ViewBag.Title = "Result";
}

<style>
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;
    }

    .row {
        display: flow-root !important;
    }

    [data-stile] {
        width: 70px;
        height: 70px;
        padding: 10px;
        border: 1px solid #aaaaaa;
    }

    .post-options {
        background-color: transparent !important;
        border-top: none !important;
    }

    .post-option:hover {
        background-color: transparent !important;
    }
    body, html {
        height: 100%;
        margin: 0;
    }

    .fondo {
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .centervertical {
        margin: 0;
        position: relative;
        top: 30%;
        -ms-transform: translateY(-30%);
        transform: translateY(-30%);
    }
</style>

<div class="fondo" style="background-image: url('@Url.Content("../../Content/assets/img/Fondos/Fondo_Avatar.png")');">


    <div data-reto class="centervertical">
        <br />
        <br />
        <div class="grid grid-4-4-4 centered">
            <div class="grid-column">
                <h1 style="text-align:center; color:black"> Resultado del Juego </h1>
            </div>
        </div>
        <br />
        <div class="grid grid-half change-on-desktop centered">
            <div class="grid-column center">
                <img src="@Url.Content("~/Content/assets/img/fig4.PNG")" width="385" height="385" />
            </div>
            <div class="grid-column card" style="opacity:0.8;padding-top:40px;padding-bottom:40px">
                @foreach (var item in Model.ListDetailNota)
                {
                    <h1 style="text-align:center; color:black">
                        @item.Item1 : @item.Item2 puntos
                    </h1>
                }
                <hr />
                <h1 style="text-align:center; color:black;font-size: 60px;font-weight: bold;"> @Model.MensajeFinal</h1>
            </div>


        </div>
        <br />
        <br />
        <div class="grid grid-4-4-4 centered">
            <div class="grid-column">
                <a class="btn" style="background-color:orange;  color:black;font-size: 20px;font-weight: bold;" href="@Url.Action("Games", "Numeration", new { TemaId = Model.Ejercicio.TemaId, LevelBIA = Model.Ejercicio.LevelBIA})">
                    SALIR
                </a>
            </div>
        </div>
    </div>
</div>