SistemaLudico/ViewModels/MainStudent/GameViewModel.cs
using SistemaLudico.Controllers;
using SistemaLudico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaLudico.ViewModels.MainStudent
{
    public class GameViewModel
    {
        public Int32? TemaId { set; get; }
        public String LevelBIA { set; get; }
        public Int32? JuegoId { set; get; }
        public List<Ejercicio> ListLevelBIA { set; get; } = new List<Ejercicio>();
        public List<Progreso> ListProgreso { set; get; } = new List<Progreso>();
        public Boolean ActivateCalificacion { set; get; }
        HttpContext context = HttpContext.Current;

        public void Fill(CargarDatosContext cd, Int32? temaId, String levelBIA) {
            this.TemaId = temaId;
            this.LevelBIA = levelBIA;
            this.ListLevelBIA = cd.context.Ejercicio.Where(x => x.LevelBIA == this.LevelBIA && x.TemaId == this.TemaId).OrderBy(x=>x.LevelGame).ToList();
            this.JuegoId = cd.context.Ejercicio.FirstOrDefault(x => x.LevelBIA == this.LevelBIA && x.TemaId == this.TemaId).JuegoId;
            var participanteId = (int)(context.Session["PARTICIPANTEID"]);
            var lstProgreso = cd.context.Progreso.Where(x => x.ParticipanteId == participanteId && x.Ejercicio.JuegoId == JuegoId && x.Ejercicio.LevelBIA == LevelBIA && x.Nota > 0).ToList();
            this.ListProgreso = cd.context.Progreso.Where(x => x.ParticipanteId == participanteId && x.Ejercicio.JuegoId == JuegoId && x.Ejercicio.LevelBIA == LevelBIA).ToList(); ;
            if (lstProgreso.Count() == 5) {
                this.ActivateCalificacion = true;
            }
            else{
                this.ActivateCalificacion = false;
            }
        }
    }
}

SistemaLudico/ViewModels/MainStudent/LevelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaLudico.ViewModels.MainStudent
{
    public class LevelViewModel
    {
        public Int32? TemaId { set; get; }
        public void Fill(Int32? temaId) {
            this.TemaId = temaId;
        }
    }
}

SistemaLudico/ViewModels/MainStudent/ResultViewModel.cs
using SistemaLudico.Controllers;
using SistemaLudico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SistemaLudico.ViewModels.MainStudent
{
    public class ResultViewModel
    {
        public string MensajeFinal { set; get; }
        public Ejercicio Ejercicio { set; get; } = new Ejercicio();
        HttpContext context = HttpContext.Current;
        public List<Tuple<string, int>> ListDetailNota { set; get; } = new List<Tuple<string, int>>();

        public void Fill(CargarDatosContext cd, Int32? EjercicioId, Int32? Vidas) {
            this.Ejercicio = new Ejercicio();
            this.Ejercicio = cd.context.Ejercicio.FirstOrDefault(x => x.EjercicioId == EjercicioId);
            var nota = 0;
            var participanteId = (int)(context.Session["PARTICIPANTEID"]);
            switch (Vidas) {
                case 1:
                    this.MensajeFinal = "Haz obtenido 2 puntos";
                    nota = 2;
                    break;
                case 2:
                    this.MensajeFinal = "Haz obtenido 3 puntos";
                    nota = 3;
                    break;
                case 3:
                    this.MensajeFinal = "Haz obtenido 4 puntos";
                    nota = 4;
                    break;
            }

            var progreso = new Progreso();

            if (cd.context.Progreso.Any(x => x.EjercicioId == EjercicioId && x.ParticipanteId == participanteId))
            {
                progreso = cd.context.Progreso.FirstOrDefault(x => x.EjercicioId == EjercicioId && x.ParticipanteId == participanteId);
                if (nota > progreso.Nota) {
                    progreso.Nota = nota;
                }
                cd.context.SaveChanges();

                //validar si ya existe el siguiente
                var nextLevel = (Ejercicio.LevelGame + 1);
                var ejercicioNext = cd.context.Ejercicio.FirstOrDefault(x => x.LevelGame == nextLevel && x.TemaId == Ejercicio.TemaId);

                if (!cd.context.Progreso.Any(x => x.ParticipanteId == participanteId && x.EjercicioId == ejercicioNext.EjercicioId)) {
                
                    var progresoFuture = new Progreso();
                    cd.context.Progreso.Add(progresoFuture);
                    progresoFuture.ParticipanteId = participanteId;
                    progresoFuture.EjercicioId = ejercicioNext.EjercicioId;
                    progresoFuture.Nota = 0;
                    cd.context.SaveChanges();
                }
            }
            else
            {
                /*cd.context.Progreso.Add(progreso);
                progreso.ParticipanteId = participanteId;
                progreso.EjercicioId = EjercicioId;
                progreso.Nota = nota;
                cd.context.SaveChanges();*/
            }
        }
        public void FillResultLevelBIA(CargarDatosContext cd, Int32? JuegoId, String LevelBIA)
        {
            var participanteId = (int)(context.Session["PARTICIPANTEID"]);
            var puntuacion = new Puntuacion();
            var listProgreso = cd.context.Progreso.Where(x => x.ParticipanteId == participanteId && x.Ejercicio.JuegoId == JuegoId && x.Ejercicio.LevelBIA == LevelBIA).ToList();
            this.Ejercicio = cd.context.Ejercicio.FirstOrDefault(x => x.JuegoId == JuegoId);
            if (cd.context.Puntuacion.Any(x => x.JuegoId == JuegoId && x.ParticipanteId == participanteId && x.LevelBIA == LevelBIA))
            {
                puntuacion = cd.context.Puntuacion.FirstOrDefault(x => x.JuegoId == JuegoId && x.ParticipanteId == participanteId && x.LevelBIA == LevelBIA);
                puntuacion.Nota = listProgreso.Sum(x => x.Nota).Value;
            }
            else
            {
                cd.context.Puntuacion.Add(puntuacion);
                puntuacion.Nota = listProgreso.Sum(x => x.Nota).Value;
                puntuacion.ParticipanteId = participanteId;
                puntuacion.JuegoId = JuegoId.Value;
                puntuacion.LevelBIA = LevelBIA;
            }
            cd.context.SaveChanges();

            foreach(var item in listProgreso) {
                this.ListDetailNota.Add(new Tuple<string, int>("Ejercicio " + item.Ejercicio.LevelGame, item.Nota.Value));
            }

            var level = String.Empty;
            switch (LevelBIA) {
                case "BAS":
                    level = "BÁSICO";
                    break;
                case "INT":
                    level = "INTERMEDIO";
                    break;
                case "AVA":
                    level = "AVANZADO";
                    break;
            }
            var juego = cd.context.Juego.FirstOrDefault(x => x.JuegoId == JuegoId);
            this.MensajeFinal = "Para el nivel " + level + " del tema " + juego.Tema.Nombre + " ha obtenido un total de " + puntuacion.Nota.ToString();
        }
    }
}

SistemaLudico/Controllers/GeometriController.cs
using SistemaLudico.ViewModels.MainStudent;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SistemaLudico.Controllers
{
    public class GeometriController : BaseController
    {
        public ActionResult Level(Int32? TemaId)
        {
            LevelViewModel vm = new LevelViewModel();
            vm.Fill(TemaId);
            return View(vm);
        }
        public ActionResult Games(Int32? TemaId, String LevelBIA)
        {
            GameViewModel vm = new GameViewModel();
            vm.Fill(CargarDatosContext(), TemaId, LevelBIA);
            return View(vm);
        }
        public ActionResult JuegoPlanas(Int32? TemaId, Int32? LevelGame)
        {
            JuegoViewModel vm = new JuegoViewModel();
            vm.Fill(CargarDatosContext(), TemaId, LevelGame);
            return View(vm);
        }
        public ActionResult JuegoLineas(Int32? TemaId, Int32? LevelGame)
        {
            JuegoViewModel vm = new JuegoViewModel();
            vm.Fill(CargarDatosContext(), TemaId, LevelGame);
            return View(vm);
        }
        public ActionResult JuegoCuerpo(Int32? TemaId, Int32? LevelGame)
        {
            JuegoViewModel vm = new JuegoViewModel();
            vm.Fill(CargarDatosContext(), TemaId, LevelGame);
            return View(vm);
        }

        public ActionResult Result(Int32? EjercicioId, Int32? Vidas)
        {
            ResultViewModel vm = new ResultViewModel();
            vm.Fill(CargarDatosContext(), EjercicioId, Vidas);
            return View(vm);
        }
        public ActionResult ResultByTopic(Int32? JuegoId, String LevelBIA)
        {
            ResultViewModel vm = new ResultViewModel();
            vm.FillResultLevelBIA(CargarDatosContext(), JuegoId, LevelBIA);
            return View(vm);
        }

        public JsonResult CalculatePlana(string Resp, Int32? EjercicioId)
        {
            try
            {
                var ejercicio = context.Ejercicio.FirstOrDefault(x => x.EjercicioId == EjercicioId);
                if (Resp != ejercicio.Resultado.ToLower())
                {
                    var result = new
                    {
                        value = "false",
                        mensaje = "La operacion es incorrecta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new
                    {
                        value = "true",
                        mensaje = "La operacion es correcta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("false", JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult CalculateLinea(string Resp, Int32? EjercicioId)
        {
            try
            {
                var ejercicio = context.Ejercicio.FirstOrDefault(x => x.EjercicioId == EjercicioId);
                var test = ejercicio.Resultado.ToLower();
                if (Resp != ejercicio.Resultado.ToLower())
                {
                    var result = new
                    {
                        value = "false",
                        mensaje = "La operacion es incorrecta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new
                    {
                        value = "true",
                        mensaje = "La operacion es correcta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("false", JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult CalculateCuerpo(string Resp, Int32? EjercicioId)
        {

            try
            {
                var ejercicio = context.Ejercicio.FirstOrDefault(x => x.EjercicioId == EjercicioId);
                if (Resp != ejercicio.Resultado.ToLower())
                {
                    var result = new
                    {
                        value = "false",
                        mensaje = "La operacion es incorrecta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var result = new
                    {
                        value = "true",
                        mensaje = "La operacion es correcta"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("false", JsonRequestBehavior.AllowGet);
            }
        }

    }
}

SistemaLudico/Views/Geometri/Games.cshtml
@model SistemaLudico.ViewModels.MainStudent.GameViewModel
@{
    ViewBag.Title = "Games";
}

<style>
    body, html {
        height: 100%;
        margin: 0;
    }

    .fondo {
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .centervertical {
        margin: 0;
        position: sticky;
        top: 30%;
        -ms-transform: translateY(-30%);
        transform: translateY(-30%);
    }
    .candado {
        background-image:url('@Url.Content("../../Content/assets/img/iconos/candado.png")');
        background-repeat: no-repeat;
        background-size: 40px 40px;
    }
</style>

<div class="fondo" style="background-image: url('@Url.Content("../../Content/assets/img/fig16.jpg")');">
    <div class="row centervertical">
        <div class="col-lg-1" style="margin-top:10%">
        </div>
        @{ var contador = 0;}
        @foreach (var item in Model.ListLevelBIA)
        {
            if (@contador % 2 == 0)
            {
                <div class="col-lg-2" style="margin-top:8%">
                    @if (Model.ListProgreso.Any(x => x.EjercicioId == item.EjercicioId))
                    {
                        <a class="col-lg-12 button small" style="background-color:blue;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action(item.Juego.Action, item.Juego.Controller, new { TemaId = Model.TemaId, LevelGame = item.LevelGame })">JUEGO @item.LevelGame</a>
                    }
                    else
                    {
                        <a class="col-lg-12 button small @(item.LevelGame == 1 ? "" : "candado")" style="background-color:blue;  color:white;font-size: 20px;font-weight: bold;" data-send data-block>JUEGO @item.LevelGame</a>
                    }
                </div>
            }
            else
            {
                <div class="col-lg-2" style="margin-top:18%">
                    @if (Model.ListProgreso.Any(x => x.EjercicioId == item.EjercicioId))
                    {
                        <a class="col-lg-12 button small" style="background-color:blue;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action(item.Juego.Action, item.Juego.Controller, new { TemaId = Model.TemaId, LevelGame = item.LevelGame })">JUEGO @item.LevelGame</a>

                    }
                    else
                    {
                        <a class="col-lg-12 button small candado" style="background-color:blue;  color:white;font-size: 20px;font-weight: bold;" data-send data-block>JUEGO @item.LevelGame</a>

                    }
                </div>
            }
            contador++;
        }
        <div class="col-lg-1" style="margin-top:10%">
        </div>
    </div>
    <div class="row" style="margin-top:400px">
        <div class="col-lg-1">
        </div>
        <div class="col-lg-2">
            <a class="col-lg-12 button small" style="background-color:red;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("Level","Geometri", new { TemaId = Model.TemaId })">ATRAS</a>
        </div>
        <div class="col-lg-2">
        </div>
        <div class="col-lg-2">
        </div>
        <div class="col-lg-2">
        </div>
        <div class="col-lg-2">
            @if (Model.ActivateCalificacion)
            {
                <a class="col-lg-12 button small" style="background-color:yellow;  color:black;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("ResultByTopic", "Geometri", new { JuegoId = Model.JuegoId, LevelBIA = Model.LevelBIA })">CALCULAR PUNTAJE FINAL</a>
            }
        </div>
    </div>
</div>

@section scripts{
    <script>
       $('[data-block]').on('click', function () {
           Swal.fire(
               "Para desbloquear este nivel debe finalizar los ejercicios anteriores",
               '',
               'warning'
           )
       });
    </script>
}

SistemaLudico/Views/Geometri/JuegoCuerpo.cshtml
@model SistemaLudico.ViewModels.MainStudent.JuegoViewModel
@{
    ViewBag.Title = "Juego1";
    int vidas = 3;
    int k = 1;
}

<style>
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 30%;
    }

    .row {
        display: flow-root !important;
    }

    [data-stile] {
        width: 100px;
        height: 100px;
        padding: 10px;
        border: 1px solid #aaaaaa;
    }
    /*[data-stile-2] {
        width: 100px;
        height: 100px;
        padding: 10px;
        border: 1px solid #aaaaaa;
    }*/

    .post-options {
        background-color: transparent !important;
        border-top: none !important;
    }

    .post-option:hover {
        background-color: transparent !important;
    }

    body, html {
        height: 100%;
        margin: 0;
    }

    .fondo {
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .centervertical {
        margin: 0;
        position: relative;
        top: 45%;
        -ms-transform: translateY(-45%);
        transform: translateY(-45%);
    }
</style>


<div class="fondo" style="background-image: url('@Url.Content("../../Content/assets/img/Fondos/Fondo_Geometria.png")');">
    <div class="centervertical">
        <div class="grid grid-4-4-4 centered">
            <div class="grid-column">
                <div class="post-options" style="margin-top:20px" data-vidas>
                    @for (int i = 0; i < vidas; i++)
                    {
                        <div class="post-option">
                            <img src="@Url.Content("~/Content/assets/img/corazon.png")" width="70" height="70" />
                        </div>
                    }
                </div>
            </div>
            <div class="grid-column">
            </div>
            <div class="grid-column">
            </div>
        </div>

        <div data-reto>
            <div class="grid grid-4-4-4 centered">
                <div class="grid-column">
                    <h1 style="text-align:center; color:black"> RETO @Model.Ejercicio.LevelGame</h1>
                </div>
            </div>
            <br />
            <div class="grid grid-4-4-4 centered">
                <div class="grid-column">
                    <img src="@Url.Content("~/Content/assets/img/personajes/batman_cuerpos.png")" width="385" height="300" style="margin:10px" />
                </div>
                <div class="grid-column">
                    <img src="@Url.Content(Model.Ejercicio.RutaImagen)" width="" height="385" style="transform:translateX(-15%)" />
                </div>
                <div class="grid-column">
                    <div class="widget-box" style="margin-right:-15px">
                        <div class="post-options" style="padding:0px;margin-bottom:40px">
                            <div class="post-option">
                                <div id="div1" ondragover="allowDrop(event)" data-stile style="border-radius: 12px;">
                                    <img id="val-cilindro" src="@Url.Content("~/Content/assets/img/problem/geometri/cuerpos/cilindro.PNG")" width="100" height="100" draggable="true" ondragstart="drag(event)" />
                                </div>
                            </div>
                            <div class="post-option">
                                <div id="div2" ondragover="allowDrop(event)" data-stile style="border-radius: 12px;">
                                    <img id="val-cono" src="@Url.Content("~/Content/assets/img/problem/geometri/cuerpos/cono.PNG")" width="100" height="100" draggable="true" ondragstart="drag(event)" />
                                </div>
                            </div>
                            <div class="post-option">
                                <div id="div3" ondragover="allowDrop(event)" data-stile style="border-radius: 12px;">
                                    <img id="val-esfera" src="@Url.Content("~/Content/assets/img/problem/geometri/cuerpos/esfera.PNG")" width="100" height="100" draggable="true" ondragstart="drag(event)" />
                                </div>
                            </div>
                        </div>
                        <br />
                        <div class="post-options" style="padding:0px;margin-bottom:40px">
                            <div class="post-option">
                                <div id="div4" ondragover="allowDrop(event)" data-stile style="border-radius: 12px;">
                                    <img id="val-prisma" src="@Url.Content("~/Content/assets/img/problem/geometri/cuerpos/prisma.PNG")" width="100" height="100" draggable="true" ondragstart="drag(event)" />
                                </div>
                            </div>
                            <div class="post-option">
                            </div>
                            <div class="post-option">
                                <div id="div6" ondragover="allowDrop(event)" data-stile style="border-radius: 12px;">
                                    <img id="val-cubo" src="@Url.Content("~/Content/assets/img/problem/geometri/cuerpos/cubo.PNG")" width="100" height="100" draggable="true" ondragstart="drag(event)" />
                                </div>
                            </div>
                        </div>
                        <br />
                    </div>
                </div>
            </div>
            <br />
            <br />
            <div class="grid grid-3-9  centered" style="margin-top:5px !important">
                <div class="grid-column">
                    <div id="trash" class="center" ondrop="dropTrash(event)" ondragover="allowDrop(event)" data-stile-2 style="border-radius: 12px;background-image: url('@Url.Content("/Content/assets/img/trash.png")');background-size: 140px 97px;height:97px">

                    </div>
                </div>
                <div class="grid-column widget-box" style="margin:15px;padding-top: 35px;padding-bottom: 35px;">
                    <div class="post-options" style="padding:0px">
                        <div class="post-option" style="width: 300px;">
                            <div id="response" style="margin-right:20px">
                                <h3>Seleccion y arrastre la figura correcta</h3>
                            </div>
                        </div>
                        <div class="post-option">
                            <div id="response" style="margin-right:20px" class="center">
                                <div id="respreto1" ondrop="dropResponse(event)" ondragover="allowDrop(event)" data-stile style="border-radius: 12px;">
                                </div>
                            </div>
                        </div>
                        <div class="post-option">
                            <a class="btn" style="background-color:orange;  color:white;font-size: 20px;font-weight: bold;" data-validate>
                                Verificar Respuesta
                            </a>
                            <a class="btn" style="background-color:green;  color:white;font-size: 20px;font-weight: bold;" hidden="hidden" data-next>
                                Resultado
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<audio id="fondomusic" controls="controls" autoplay="autoplay" hidden>
    <source src="@Url.Content("~/Content/assets/img/music/Canci%c3%b3n%20de%20Super%20Mario%20Bros.%20(192%20%20kbps).mp3")" type="audio/mpeg" />
</audio>



@section scripts{
    <script>
            var audioElementCorrecto = document.createElement('audio');
        var audioElementIncorrecto = document.createElement('audio');
        var audioElementGameOver = document.createElement('audio');

        audioElementCorrecto.setAttribute('src', '@Url.Content("~/Content/assets/img/music/Ni%c3%b1os%20Gritan%20Yay!!!%20(Efecto%20de%20Sonido)%20(192%20%20kbps)%20(1).mp3")');
        audioElementIncorrecto.setAttribute('src', '@Url.Content("~/Content/assets/img/music/Respuesta%20incorrecta%20(Efecto%20de%20Sonido)%20Wrong%20Buzzer%20%20Sound%20Effect%20(192%20%20kbps).mp3")');
        audioElementGameOver.setAttribute('src', '@Url.Content("~/Content/assets/img/music/Super%20Mario%20Game%20over%20sound%20effect%20(Origianl)%20(192%20%20kbps).mp3")');

            var vida = 3;
        $('[data-validate]').on('click', function () {
            var resp = $('#respreto1')[0].children[0] == undefined ? "" : $('#respreto1')[0].children[0].id;
            var resG = resp;
            var ejercicioId = @Model.Ejercicio.EjercicioId
                $.ajax({
                    url: '@Url.Action("CalculateCuerpo", "Geometri")',
                    type: 'GET',
                    data: { Resp: resG, EjercicioId: ejercicioId },
                    success: function (data) {
                        debugger;
                        if (data.value === "false") {
                            vida = vida - 1;

                            var vidas = '';
                            for (var i = 0; i < vida; i++) {
                                vidas = vidas + '<div class="post-option"> <img src="@Url.Content("~/Content/assets/img/corazon.png")" width="70" height="70" /> </div>';
                            }
                            for (var i = vida; i < 4; i++) {
                                vidas = vidas + ' <div class="post-option"></div>';
                            }
                            $('[data-vidas]').empty();
                            $('[data-vidas]').append(vidas);

                            if (vida == 0) {

                                    var audioplayer = document.getElementById("fondomusic");
                                    audioplayer.pause();
                                    audioElementGameOver.play();
                                    Swal.fire(
                                        "No le quedan vidas :( ",
                                        '',
                                        'error'
                                    )
                                    
                                    setTimeout(function () {
                                        window.location.href = "http://localhost:53995/Geometri/Games?TemaId=@Model.TemaId&LevelBIA=@Model.LevelBIA";
                                    }, 4000);
                                    e.preventDefault();
                                    return false;
                                }
                            audioElementIncorrecto.play();

                            Swal.fire(
                                data.mensaje,
                                '',
                                'error'
                            )
                        } else {
                            $("[data-next]").removeAttr("hidden");
                            $("[data-validate]").prop("hidden", "hidden");
                            audioElementCorrecto.play();
                            Swal.fire(
                                data.mensaje,
                                '',
                                'success'
                            )
                        }

                    }
                });
        });

            $('[data-next]').on('click', function () {
                window.location.href = "http://localhost:53995/Geometri/Result?EjercicioId=" + @Model.Ejercicio.EjercicioId + "&Vidas=" + vida;
            });

            var lastShape;
            function allowDrop(ev) {
                ev.preventDefault();
            }
            function drag(ev) {
                lastShape = ev.currentTarget.parentElement.id;
                ev.dataTransfer.setData("text", ev.target.id);
            }
            function dropTrash(ev) {
                debugger;
                ev.preventDefault();
                var data = ev.dataTransfer.getData("text");

                //ev.target.appendChild(document.getElementById(data));
                var eliminar = "#" + ev.currentTarget.id;
                $(eliminar).empty();
                if (lastShape === 'respreto1') {
                    var id = '#' + lastShape;
                    $(id).empty();
                }
            }
            function dropResponse(ev) {
                debugger;
                ev.preventDefault();
                var data = ev.dataTransfer.getData("text");
                var clone = document.getElementById(data).outerHTML.replace('val-', '');
                var destino = "#" + ev.currentTarget.id;
                $(destino).empty();
                $(destino).append(clone)
                if (lastShape === 'respreto1' ) {
                    var id = '#' + lastShape;
                    $(id).empty();
                }
            }
    </script>
}

SistemaLudico/Views/Geometri/Level.cshtml
@model SistemaLudico.ViewModels.MainStudent.LevelViewModel
@{
    ViewBag.Title = "Level";
}

<style>
    .center {
        display: block;
        margin-left: auto;
        margin-right: auto;
        width: 50%;
    }
    body, html {
        height: 100%;
        margin: 0;
    }

    .fondo {
        height: 100%;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    .centervertical {
        margin: 0;
        position: absolute;
        top: 30%;
        -ms-transform: translateY(-30%);
        transform: translateY(-30%);
    }
</style>

<div class="fondo" style="background-image: url('@Url.Content("../../Content/assets/img/fig16.jpg")');">
    <div class="row">
        <div class="col-lg-4" style="margin-top:10%">
            <img src="@Url.Content("~/Content/assets/img/gift/7.gif")" class="center" width="310" height="310"/>
            <a class="col-lg-12 button small" style="background-color:forestgreen;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("Games","Geometri", new { TemaId = Model.TemaId, LevelBIA = "BAS" })">BASICO</a>
        </div>
        <div class="col-lg-4" style="margin-top:10%">
            <img src="@Url.Content("~/Content/assets/img/gift/3.gif")" class="center" width="310" height="310"/>
            <a class="col-lg-12 button small" style="background-color:darkorange;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("Games","Geometri", new { TemaId = Model.TemaId, LevelBIA = "INT"})">INTERMEDIO</a>
        </div>
        <div class="col-lg-4" style="margin-top:10%">
            <img src="@Url.Content("~/Content/assets/img/gift/8.gif")" class="center" width="310" height="310"/>
            <a class="col-lg-12 button small" style="background-color:red; color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("Games","Geometri", new { TemaId = Model.TemaId, LevelBIA = "AVA" })">AVANZADO</a>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-1" style="margin-top:10%">
        </div>
        <div class="col-lg-2" style="margin-top:12%">
            <a class="col-lg-12 button small" style="background-color:red;  color:white;font-size: 20px;font-weight: bold;" data-send href="@Url.Action("TemaStart","MainStudent", new { TemaId = Model.TemaId })">ATRAS</a>
        </div>
    </div>
</div>